### ISSUE TITLE
Melhorias no countdown time

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#1]
@Webchu duas coisas que te falei que precisamos:
- tirar o start automático
- fazer o fundo ficar vermelho quando estiver nos últimos segundos (e talvez verde quando estiver começando, a testar)

**Comment by thiagoesser** [comment]
@Webchu 
Outras funcionalidades que vão ser úteis:
- Poder escolher o tempo total. Isso pode variar entre 2min (lightning talks), 5min, 25min, 35min. Mais ou menos esses tempos. Talvez a gente possa fazer um acesso rápido pro cara que estiver ali controlando na hora, um link pra setar esses tempos.
- Zerar o relógio (isto é, voltar para o último valor cheio, seja de 5, 25min...)

**Comment by Webchu** [comment]
Ajustes realizados:
- não faz mais o start automático
- seta classe para deixar o fundo vermelho quando chegar nos 15 segundos finais (configurável)
- tratamento de eventos via hashchange
- eventos possíveis: start, pause
- combo para seleção de tempos (configurável)
- tempo e eventos podem ser informados diretamente na URL. Ex.: http://thiagoesser.github.io/uxconf/countdown.html#01:00 _(Obs.: deve seguier o padrão MM:SS)_

**Comment by thiagoesser** [comment]
Ficou show! Acho que agora é largar a camada visual ali.

@Webchu rola um botão de zerar o contador? algo que equivaleria a dar um refresh na página, só que em forma de link (assim como start e stop). acho que vai ser útil lá na hora

**Comment by thiagoesser** [comment]
@Webchu ah, outra meio bobinha, mas que faz diferença na prática: quando o relógio zera de vez, depois de ter piscado por 15 segundos, ele para de piscar, e fica com o vermelho fixo no fundo. 

como que dizendo, "agora não é mais um alerta, agora fechou mesmo". sacou?

**Comment by Webchu** [comment]
Rola sim!
Vou deixar ele todo funcional e depois vou pro visual.

2016-05-09 10:51 GMT-03:00 Thiago Esser notifications@github.com:

**Comment by Webchu** [comment]
Rola também.
Como é setada uma classe quando entra nos 15s finais, posso setar uma outra
quando chegar no 0!
Dá pra fazer chover se tu quiser! :D

Em 9 de maio de 2016 10:55, Thiago Esser notifications@github.com
escreveu:

**Comment by thiagoesser** [comment]
@Webchu vamos fazer chover então! haha. Outra ideia: quando chegar no 00:00, além de ficar todo  vermelho, ele mostra a plavras APLAUSOS, como num programa de TV :)

**Comment by Webchu** [comment]
huuahuhahua!
show!
vou fazer subir uma plaquinha com a palavra "APLAUSOS"

Em 9 de maio de 2016 14:51, Thiago Esser notifications@github.com
escreveu:

**Comment by thiagoesser** [comment]
Mexi no visu :)

**Comment by thiagoesser** [comment]
Dá pra barra de espaço do teclado ativar play ou pause? Pode ser útil.
