### ISSUE TITLE
Sisteminha de sorteios de nomes 

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#2]
@Webchu A estudar uma forma fácil de fazer isso.

**Comment by Webchu** [comment]
Tinha pensado em algo assim:
http://thiagoesser.github.io/uxconf/random.html

Loops:
- 1 e 2: rapidão
  3: um pouco mais lento
  4: mais lento ainda
  5: super lento pra dar o suspense

O que achas?

**Comment by thiagoesser** [comment]
@webchu rapidao. sabe por que? alguem pode ficar constrangido de ter seu nome claramente exposto. a não ser que ganhe mas aí não dá pra fugir mesmo.

o que já vi era um como se fosse uma roleta onde dava pra ler mais ou menos os nomes, pela velocidade, e eles meio que se sobrepunham.

**Comment by thiagoesser** [comment]
@Webchu 
Uma questão: temos como trabalhar de uma jeito que ele funcione mesmo se estiver sem internet? Tipo alguma coisa que fica em cache, seilá. Tanto o sorteador quanto o counter.

**Comment by Webchu** [comment]
Sim. Hj tá pegando de um CDN, mas posso deixar pegando do arquivo local.

Em 9 de maio de 2016 14:53, Thiago Esser notifications@github.com
escreveu:

**Comment by Webchu** [comment]
@thiagoesser 
Dá um conferis como ficou:
http://thiagoesser.github.io/uxconf/random.html#self

Dá pra aumentar ou diminuir os tempos.

Avalia e me avisa, pls.

**Comment by thiagoesser** [comment]
Acho que tá beleza @Webchu ! Dá pra aumentar o tempo que ficar rodando pra dar mais suspense. Quanto tá agora, 1s ou 2s? Dá pra deixar uns 5s, acho.

**Comment by Webchu** [comment]
Tá em ms.
o que dá pra aumentar é a quantidade de voltas. Atualmente ele para na 30º
volta, porém, como o tempo tá bem rápido, acaba rápido, além de serem
poucos nomes, né.
Posso aumentar para umas 60 voltas ou mais.

2016-05-12 10:46 GMT-03:00 Thiago Esser notifications@github.com:

**Comment by thiagoesser** [comment]
Bota 320 nomes pra ficar mais realista.

**Comment by thiagoesser** [comment]
Fiz um commit aqui de ajustes pequenos. Consegue deixar o tamanho dos nomes e do botão mais considerável? :)

**Comment by thiagoesser** [comment]
@webchu nice to have pros dois casos : os controles de play pause etc. ficarem numa pop up separada da roleta ou counter, aparecendo só para o controlador

**Comment by thiagoesser** [comment]
tu tem um jeito fácil de converter os 350 nome para UL LI?faz essa mão?

**Comment by thiagoesser** [comment]
@Webchu tem vezes que no meio da rodada ele parece dar uma travadinha. se puder dar uma sua nessa transição... (e se conseguir visuaçizar o que estou falando)

**Comment by thiagoesser** [comment]
@Webchu 
- pra melhorar a impressão também, podes diminuir o espaçamento entre os itens. o atual deixa uns buracos na hora que rola
  - quando entro pela primeira vez ou dou refresh, não deve aparecer nenhum nome por padrão (senão a pinta vai achar que foi sorteada hehe)
