### ISSUE TITLE
Acrecentar nova opção de tempo no contador (10:00)

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#4]
Esse ano também teremos palestras de 10min. Acrescentar essa opção na combo-box.

**Comment by Webchu** [comment]
Opção acrescentada.

**Comment by thiagoesser** [comment]
Grande @Webchu ! Foi mal, mas esqueci de te pedir pra também adicionar a modalidade 30:00, que serão nossos keynotes :)

**Comment by Webchu** [comment]
Feito!
