### ISSUE TITLE
Criar uma forma alternativa de "subir" nomes dos sorteados.

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#5]
Hoje em dia conseguimos alimentar os nomes dos sorteados somente colocando-os direto no html, o que é trabalhoso para pessoas que não tem fluencia em front-end, nem posse das ferramentas para fazer isso de forma prática (um evento é composto de pessoas de skills muito variados).

Gostaríamos de alimentar o sorteador através de um arquivo que possa ser referenciado "localmente"(*), por exemplo: dentro de um pasta **/names** (ou semelhante), dentro do projeto, coloco um arquivo **.txt** com um nome por linha, e quando fizer uma alteração nesse arquivo, o sorteador pegará novos nomes ou eliminará a partir dele.   

(*) Importante manter ele sempre rodando sem necessidade de internet, como já é agora, e **sem** necessidade de rodar servidor local (gulp da vida).

**Comment by Webchu** [comment]
Implementada a nova forma de carga de nome.
Para "subir" um arquivo, pressione a letra "f" e selecione o arquivo com os nomes.
O formato é:

nome 1
nome 2
nome 3
...
