### ISSUE TITLE
Ajustes de fonte/visual do Contador

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#6]
A fonte passa a ser a Share Tech Mono, [disponível no Google Fonts](https://fonts.google.com/specimen/Share+Tech+Mono), tanto para o relógio quanto para o aviso de aplauso. Ela deve ser adicionada ao projeto e baixada junto quando for rodada "localmente" (simplesmente baixando os arquivos para a máquina, sem localhost nem nada, como já é hoje).

**Imagens do resultado pretendido**: 

![captura de tela 2017-05-12 as 17 29 55](https://cloud.githubusercontent.com/assets/1593518/26017669/2b63d954-3741-11e7-8b38-f51e3eba8fb5.png)

![captura de tela 2017-05-12 as 18 08 33](https://cloud.githubusercontent.com/assets/1593518/26017699/511f9016-3741-11e7-8ce8-9e2fdefd7fe4.png)

**Tamanho aproximado da fonte do relógio** numa viewport mais ou menos 1200px de largura, com espaçamento de letras customizado: `#countdown {font-size: 30em; letter-spacing: -30px;}`

**Tamanho aproximado da fonte do relógio** numa viewport mais ou menos 1200px de largura: `body.finish .applauses { font-size: 160px;}`

**Comment by Webchu** [comment]
Alterada a fonte e os estilos solicitados.
Validar como se comporta no Mac.

**Comment by thiagoesser** [comment]
Se comporta de maneira muito rude e mal educada no mac, haha.

**Comment by Webchu** [comment]
hahaha
Dei um jeito nesse safado!
Acho que agora tá carregando corretamente.

**Comment by thiagoesser** [comment]
lindo! chu gênio!!
