### ISSUE TITLE
Ajuste de fonte/visual do Sorteador

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#7]
A fonte passa a ser a Share Tech Mono, disponível no Google Fonts e usada também no contador. Ela deve ser adicionada ao projeto e baixada junto quando for rodada "localmente" (simplesmente baixando os arquivos para a máquina, sem localhost nem nada, como já é hoje).

Reposicionar o "play" acima do logo a abaixo do nome.

**Imagens do resultado pretendido:**

![captura de tela 2017-05-12 as 17 56 55](https://cloud.githubusercontent.com/assets/1593518/26018068/2e559e3e-3743-11e7-8123-e49f29ce8ecd.png)

Observação que depende do que for feito na issue #5: quando um nome já foi sorteado, o nome apareceria ~~riscado~~, após atualização do nome na lista para algo como `~~Pedro Belleza da Silva Sauro~~`.

![captura de tela 2017-05-12 as 18 05 31](https://cloud.githubusercontent.com/assets/1593518/26018117/69a07176-3743-11e7-997d-629bccc17435.png)

*Tamanho aproximado da fonte do nome* numa viewport de mais ou menos 1200px de largura: `body .wrapper ul li {line-height: 110px; font-size: 8em;}`

**Comment by Webchu** [comment]
Alterada a fonte e ajustes solicitados.

Para marcar um nome já como sorteado, siga o exemplo abaixo:

nome 1
nome 2
#nome sorteado
nome 3
...

Ou seja, basta informar um "#" no início do nome para que o mesmo já venha riscado.

**Comment by thiagoesser** [comment]
Mesma questão da outra issue (não pega a fonte certa). @Webchu um comentário quando for mexer nisso:

- Pode deixar o nome riscado com `opacity: 1` padrão mesmo, para que as pessoas da platéia consigam ler bem o nome que já saiu.

**Comment by Webchu** [comment]
Ajustada a fonte e setado opacity: 1

**Comment by thiagoesser** [comment]
Com aqueles nomes que te passei hoje ainda tá quebrando. Sugestão de mudança que testei aqui e bombou: mudar tamanho de fonte. `body .wrapper ul li  font-size: 6em;}` 

**Print com erro:** 

![captura de tela 2017-05-17 as 23 30 40](https://cloud.githubusercontent.com/assets/1593518/26184165/8edf7896-3b59-11e7-8474-fdcb310828fd.png)

**Nomes de teste**

Lorem ipsum 
Dolor sit amet
Consectetur adipiscing elit. 
Aliquam condimentum nulla 
#Nondiamtempus, sed ullamcorper mi
Rutrum. Cras non ornare felis. 
Praesent porta quam sapien. 
#Sed libero odio, accumsan 
Non massa a, auctor vulputate leo

**Print sem erro:**

![captura de tela 2017-05-17 as 23 41 39](https://cloud.githubusercontent.com/assets/1593518/26184289/653493f4-3b5a-11e7-8321-7fdcd6c8bc83.png)

**Comment by Webchu** [comment]
Feitoria!
