### ISSUE TITLE
Contador responsivo

### ISSUE THREAD

**Issue by thiagoesser** [thiagoesser/uxconf#8]
Fazer com o que o contador se adapte a viewports diferentes (desktop, tablet, smartphone), com os 4 dígitos do relógio (00:00) ocupando o maior espaço possível. Os controles (play, pause...) eventualmente pode ficar abaixo da dobra.

Essa issue não é um _must have_, mas será bom tê-la desenvolvida, no caso onde precisemos usar o relógio para ensaio de palestras ou mesmo se der algum problema no computador principal que roda o contador do evento.

**Comment by Webchu** [comment]
Realizado alguns ajustes.
Favor validar o comportamento nos devices desejados.

**Comment by thiagoesser** [comment]
Ficou tri! Só um pequeno ajuste: na media query menor que 768px, mudar para `#countdown { letter-spacing: -15px;}`.

**Comment by Webchu** [comment]
Ajustado!
